name: vdp_sde
save: false
engine:
  sde:
    # Time Domain
    t0: 0.0
    t1: 100000.0
    dt: 1.0

    # Ensemble
    n_traj: 1000
    seed: 42
    ic:
      - ["7.0+0.0j", "0.0-7.0j"]

    # Adaptive
    adaptive: false
    atol: 1e-3
    rtol: 1e-3
    min_dt: 1e-3
    max_dt: 1.0
    save_stride: 1

model:
  vdp_level3:
    omega_a: 0.005
    omega_b: 0.0
    gamma_a: 2.0
    gamma_b: 1.0
    Gamma: 0.01
    g: 0.5
    D: 1.0

backend:
  cupy:
    float_dtype: float32
    device: cuda

integrator:
  srk:
    method: heun
