[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qphase-viz"
version = "0.10.1"
description = "Visualization plugin for QPhase: Phase Portraits and PSD Analysis"
readme = "README.md"
requires-python = ">=3.10"
urls = { Homepage = "https://github.com/PolarisMegrez/qphase", Repository = "https://github.com/PolarisMegrez/qphase", Issues = "https://github.com/PolarisMegrez/qphase/issues" }
dependencies = [
    "matplotlib>=3.6",
    "numpy>=1.23",
    "scipy>=1.10",
    "qphase>=0.10.1",
    "qphase-sde>=0.10.1"
]

[project.entry-points.qphase]
"engine.viz" = "qphase_viz.engine:VizEngine"
"visualizer.phase_plane" = "qphase_viz.plotters.phase:PhasePlanePlotter"
"visualizer.power_spectrum" = "qphase_viz.plotters.spectrum:PowerSpectrumPlotter"
"visualizer.time_series" = "qphase_viz.plotters.evolution:TimeSeriesPlotter"

[tool.setuptools.packages.find]
where = ["."]
