name: vdp_run
engine: sde
model:
  vdp_two_mode:
    omega_a: 0.005
    omega_b: 0.0
    gamma_a: 2.0
    gamma_b: 1.0
    Gamma: 0.01
    g: 0.5
    D: 1.0
backend:
  numpy:
    device:  # Device identifier (e.g., 'cpu', 'cuda:0')
    float_dtype: float64 # Default floating-point dtype
    optimize_einsum: true # Enable einsum optimization
